# Generated by Django 5.0.3 on 2024-03-19 00:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cast_member_app', '0001_initial'),
        ('category_app', '0002_alter_category_description_alter_category_id'),
        ('genre_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioVideoMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checksum', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('raw_location', models.CharField(max_length=255)),
                ('encoded_location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('ERROR', 'ERROR')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ImageMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checksum', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('raw_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('launch_year', models.IntegerField()),
                ('duration', models.DecimalField(decimal_places=2, max_digits=10)),
                ('published', models.BooleanField()),
                ('rating', models.CharField(choices=[('ER', 'ER'), ('L', 'L'), ('AGE_10', 'AGE_10'), ('AGE_12', 'AGE_12'), ('AGE_14', 'AGE_14'), ('AGE_16', 'AGE_16'), ('AGE_18', 'AGE_18')], max_length=255)),
                ('banner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='video_app.imagemedia')),
                ('cast_members', models.ManyToManyField(related_name='videos', to='cast_member_app.castmember')),
                ('categories', models.ManyToManyField(related_name='videos', to='category_app.category')),
                ('genres', models.ManyToManyField(related_name='videos', to='genre_app.genre')),
                ('thumbnail', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_thumbnail', to='video_app.imagemedia')),
                ('thumbnail_half', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_thumbnail_half', to='video_app.imagemedia')),
                ('trailer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_trailer', to='video_app.audiovideomedia')),
                ('video', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_media', to='video_app.audiovideomedia')),
            ],
        ),
    ]
