sequenceDiagram
    participant Encoder as Encoder
    participant Consumer as RabbitMQConsumer (videos.converted)
    participant Processor as ProcessAudioVideoMedia
    participant VideoEntity as Video (Entity)
    participant VideoRepo as VideoRepository

    Encoder->>Consumer: Publishes event in videos.converted queue
    Consumer->>Processor: Calls ProcessAudioVideoMedia with inputs
    Processor->>VideoEntity: Calls video.process(status, encoded_location)
    Note over VideoEntity: if status is "completed", then<br/> publish video, else, fail
    Processor->>VideoRepo: Update video
